<?php 
if(!empty($this->messages)) {?>
<div class="messagelog">
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert">×</button>
        <strong>Error!</strong> <?php echo $this->messages; ?>
    </div>
</div>
<?php }?>
<div id="loginbox">
    <form id="loginform" class="form-vertical" action="/lista-proyectos" method="post">
        <p>Lista de proyectos asignados</p>
        <div class="control-group">
            <div class="controls">
                <div class="input-prepend">
                    <span class="add-on"><i class="icon-time"></i></span>
                    <select name="proyecto" id="proyecto">
                    <option value="">[Seleccione proyecto]</option>
                    <?php foreach ($this->proyectos as $val){
                       echo "<option value=".$val['id_proyecto'].">".$val['nombre']."(".$val['entidad'].")</option>"; 
                    }?>
                    </select>
                </div>
            </div>
        </div>
        <div class="form-actions">
            <span class="pull-right"><input type="submit" class="btn btn-inverse" value="Entrar" /></span>
        </div>
    </form>
</div>