<?php 
if(!empty($this->messages)) {?>
<div class="messagelog">
    <div class="alert <?=$this->msg?>">
        <button class="close" data-dismiss="alert">×</button>
        <?php echo $this->messages; ?>
    </div>
</div>
<?php }?>
<div id="loginbox">
    <form id="loginform" class="form-vertical" action="/login" method="post">
        <p>Ingrese correo electrónico y clave</p>
        <div class="control-group">
            <div class="controls">
                <div class="input-prepend">
                    <span class="add-on"><i class="icon-user"></i></span><input name="usuario" id="email" type="text" placeholder="Correo electrónico" />
                </div>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <div class="input-prepend">
                    <span class="add-on"><i class="icon-lock"></i></span><input name="clave" id="pwd" type="password" placeholder="Contraseña" />
                </div>
            </div>
        </div>
        <div class="form-actions">
            <span class="pull-left"><a href="#" class="flip-link" id="fliptorecover">¿Olvidaste tu contraseña?</a></span>
            <span class="pull-right"><input type="submit" class="btn btn-inverse" value="Login" /></span>
        </div>
    </form>
    <form id="recoverform" action="/login" class="form-vertical" method="post">
        <p>Ingrese su e-mail y le enviaremos instrucciones de cómo recuperar una contraseña.</p>
        <div class="control-group">
            <div class="controls">
                <div class="input-prepend">
                    <span class="add-on"><i class="icon-envelope"></i></span><input type="text" name="emailrecover" id="emailrecover" placeholder="Correo electrónico" />
                </div>
            </div>
        </div>
        <div class="form-actions">
            <span class="pull-left"><a href="#" class="flip-link" id="fliptologin">&lt; Regresar al login</a></span>
            <span class="pull-right"><input type="submit" class="btn btn-inverse" value="Recuperar contraseña" /></span>
        </div>
    </form>
</div>