<?php 
if(!empty($this->messages)) {?>
<div class="messagelog">
    <div class="alert <?=$this->msg?>">
        <button class="close" data-dismiss="alert">×</button>
        <?php echo $this->messages; ?>
    </div>
</div>
<?php }?>
<div id="loginbox">
    <form id="loginform" class="form-vertical" action="<?=SITE_URL?>/recuperar-clave/token/<?=$this->token?>" method="post">
        <p>Ingrese su nueva clave</p>
        <div class="control-group">
            <div class="controls">
                <div class="input-prepend">
                    <span class="add-on"><i class="icon-user"></i></span><input name="usuario" id="email" type="text" readonly="true" value="<?=$this->correo?>" placeholder="Correo electrónico" />
                </div>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <div class="input-prepend">
                    <span class="add-on"><i class="icon-lock"></i></span><input name="clave" id="pwd" type="password" placeholder="Contraseña" />
                </div>
            </div>
        </div>
        <div class="form-actions">
            <span class="pull-left"><a href="<?=SITE_URL?>/login" class="" id="">&lt; Regresar al login</a></span>
            <span class="pull-right"><input type="submit" class="btn btn-inverse" value="Cambiar clave" /></span>
        </div>
    </form>
</div>