<style>
    #tabla input, #tabla select {
        font-size:8pt
    }    
</style>
<?= $this->partial('_partials/mensajes.phtml', array('messages' => $this->messages, 'tipoMessages' => $this->tipoMessages)); ?>
<div style="float:left">
    <select id="organo" name="organo">
        <option value=''>[Seleccione órgano]</option>
        <?php
        foreach ($this->organo as $val) {
            echo "<option value=" . $val['id_organo'] . ">" . $val['organo'] . "</option>";
        }
        ?>
    </select>
    <input type="hidden" id="mapaPuesto" name="mapaPuesto" value="<?= $this->mapaPuesto ?>">
</div>
<div id="capa" style="float:left"></div>
<div id="capa_puesto" style="float:left"></div>
<a id="grabarDotacion"  role="button" class="btn tip-right" onclick="grabarDotacion()" title="Grabar">
    <li class="icon-check"></li>Grabar
</a>
<input type="hidden" value="<?=$this->rol?>" id="rol">
<div class="widget-box">
    <div class="widget-title">	
        <h5><?= $this->active ?></h5>
    </div>
    <div id="leyendaDotacion" style="font-size: 8.5pt"><br><b>Periodicidad:</b> Diaria, semanal, mensual | <b>Frecuencia:</b> (2 veces al día), (3 veces a la semana), (4 veces al mes) | 
        <b>Tiempo:</b> Minutos, horas, días | <b>Duración:</b> (30 minutos por solicitud) , (2 horas por reunión)</div>
    <br>
    <div class="widget-content nopadding">
        <table id='tablaDotacion' width="140%" class="table table-condensed table-bordered" style="font-size: 7.5pt;overflow: auto">
            <thead>
                <tr>
                    <th width="4%" style="text-align: center">#</th>
                    <th width="9%">Nivel 0</th>
                    <th width="9%">Nivel 1</th>
                    <th width="9%">Nivel 2</th>
                    <th width="9%">Nivel 3</th>
                    <th width="9%">Nivel 4</th>
                    <th width="9%">Actividad</th>
                    <th width="7%">Tarea</th>
                    <th width="9%">Periodicidad</th>
                    <th width="8%">Frecuencia</th>
                    <th width="9%">Unidad</th>
                    <th width="8%">Duración</th>
                </tr>
            </thead>
            <tbody>     
            </tbody>
        </table>
        <br>
        <table id="tablaResumen" width="30%" align="center" border="1">
            <tr><th>Puesto</th><th>Servidores Públicos</th></tr>
            <tr align="center"><td id="textoPuesto"></td><td id="dotacionPuesto">0</td></tr>
        </table>
        <div id="capa_nombre">Nombres: <input type="text" id="nombre_trabajador"></div>
        <br>
    </div>
</div>
<?= $this->partial('_partials/modal.phtml', array('model' => $this->model)); ?>