<?=$this->partial('_partials/mensajes.phtml',array('messages' => $this->messages,'tipoMessages' => $this->tipoMessages));?>
<div class="widget-box">
    <div class="widget-title">	
        <h5><?=$this->active?></h5>
    </div>
<div class="widget-content nopadding" style="height: 350px">
    <center><img src="<?=SITE_URL?>/img/logo-inicio.png"></center>
</div>
</div>
<?=$this->partial('_partials/modal.phtml',array('model' => $this->model));?>
