<?= $this->partial('_partials/mensajes.phtml', array('messages' => $this->messages, 'tipoMessages' => $this->tipoMessages)); ?>
<div class="widget-box">
    <div class="widget-title">	
        <h5><?= $this->active ?></h5>
    </div>
    <div class="widget-content nopadding">
        <table id='tablaEstadoProyecto' width="100%" class="table table-condensed table-bordered">
            <thead>
                <tr>
                    <th width="4%" style="text-align: center">#</th>
                    <th width="18%">Órgano</th>
                    <th width="18%">Unidad Orgánica</th>
                    <th width="10%">Total Puestos</th>
                    <th width="25%">Puestos sin dotación</th>
                    <th width="25%">Faltantes Pertinencia</th>
                </tr>
            </thead>
            <?php
            echo '<tbody>';
            $contador = 0;
            foreach ($this->organoUnidad as $value) {
                $contador++;
                echo "<td style='text-align:center'>" . $contador . "</td>";
                echo "<td>" . $value['organo'] . "</td>";
                echo "<td>" . $value['descripcion'] . "</td>";
                echo "<td><center>" . $value['total_puestos'] . "</center></td>";
                echo "<td>" . $value['puestos'] . "</td>";
                echo "<td>" . "" . "</td>";
                echo "</tr>";
            }
            echo '</tbody>';
            ?>
        </table>
        <br>
        <br>
    </div>
</div>
<?= $this->partial('_partials/modal.phtml', array('model' => $this->model)); ?>
