<style>
    #tablaAnaPertinencia {
        font-size:8pt
    }    
</style>
<?= $this->partial('_partials/mensajes.phtml', array('messages' => $this->messages, 'tipoMessages' => $this->tipoMessages)); ?>
<div style="float:left">
    <select id="organo" name="organo">
        <option value=''>[Seleccione órgano]</option>
        <?php
        foreach ($this->organo as $val) {
            echo "<option value=" . $val['id_organo'] . ">" . $val['organo'] . "</option>";
        }
        ?>
    </select>
</div>
<div id="capa" style="float:left"></div>
<div style="float:left">
<a id="generarExcel"  role="button" class="btn tip-right" onclick="generarExcel()" title="Exportar a Excel">
    <li class="icon-check"></li>Generar Excel
</a>
</div>



<div class="widget-box">
    <div class="widget-title">	
        <h5><?= $this->active ?></h5>
    </div>
    <div class="widget-content nopadding">
        <table id='tablaAnaPertinencia' width="65%" class="table table-condensed table-bordered">
            <thead>
                <tr>
                    <th width="5%" style="text-align: center">#</th>
                    <th width="8%">Naturaleza del Órgano</th>
                    <th width="10%">Nombre del puesto</th>
                    <th width="8%">Número de posiciones</th>
                </tr>
            </thead>
            <tbody>     
            </tbody>
        </table>
        <br>
        <br>
    </div>
</div>
<?= $this->partial('_partials/modal.phtml', array('model' => $this->model)); ?>
