<?= $this->partial('_partials/mensajes.phtml', array('messages' => $this->messages, 'tipoMessages' => $this->tipoMessages)); ?>
<div class="widget-box">
    <div class="widget-title">	
        <h5><?= $this->active ?></h5>
    </div>
    <div class="widget-content nopadding">
        <table id='tabla' width="40%" class="table table-condensed table-bordered" >
            <thead>
                <tr><th>#</th><th>Descripción</th><th>Descargar</th></tr>
            </thead>
            <tbody>
                <tr><td style="text-align:center">1</td><td>Exportar resumen del proyecto</td><td><center><a href="<?= SITE_URL ?>/admin/reportes/export-resumen">Exportar</a></center></td></tr>
            </tbody>
        </table>
    </div>
</div>
<?= $this->partial('_partials/modal.phtml', array('model' => $this->model)); ?>
