<?= $this->partial('_partials/mensajes.phtml', array('messages' => $this->messages, 'tipoMessages' => $this->tipoMessages)); ?>
<div class="widget-box">
    <div class="widget-title">	
        <h5><?= $this->active ?></h5>
    </div>
    <div class="widget-content nopadding">
        <table id='tabla' width="40%" class="table table-condensed table-bordered" >
            <thead>
                <tr><th>#</th><th>Nivel</th><th>Total</th></tr>
            </thead>
            <?php
            echo '<tbody>';
            $contador = 0;
            foreach ($this->servidores as $value) {
                $contador++;
                echo '<tr>';
                echo '<td><center>'.$contador.'</center></td>';
                echo '<td>'.$value['nivel'].'</td>';
                echo '<td><center>'.$value['dotacion'].'</center></td>';
                echo '</tr>';
            }
            echo '</tbody>';
            ?>
        </table>
    </div>
</div>
<?= $this->partial('_partials/modal.phtml', array('model' => $this->model)); ?>
