<div class="alertas alertas-info">
    <button class="close" data-dismiss="alert">×</button>
    <strong>¡Mensaje!</strong> Bienvenido al sistema.
</div>
<?php echo $this->form; ?>&nbsp;&nbsp;
<button class="btn btn-inverse" id='btnGenerarTabla' onclick="generarCrud()">Generar CRUD</button>

<div id="logGenerator" style="top:4px;width: 1150px;height: 300px;border: 1px solid;background-color: #D9EDF7;overflow: auto">

</div>
