<?=$this->partial('_partials/mensajes.phtml',array('messages' => $this->messages,'tipoMessages' => $this->tipoMessages));?>
<div class="widget-box">
    <div class="widget-title">	
        <h5><?=$this->active?></h5>
    </div>
<div class="widget-content nopadding">
    <table id='tabla' class="table table-condensed table-bordered" >
        <thead>
        <tr><th></th><th>Demo1</th><th>Fecha</th><th>Telefono</th><th>Direccion</th><th>Correo</th><th>Trabajo</th><th>Sueldo</th><th>Pais</th><th>Hijos</th><th>Nacimiento</th><th>Dni</th></tr>
        </thead>
        <?php
        echo '<tbody>';
        foreach ($this->data as $value) {
            $estado = 'checkmark.png';
            echo '<tr>';
            echo '<td width=5% class="taskOptions">';
            echo '<a data-original-title="Editar" class="tip-top" href="#myModal" data-toggle="modal" onclick="editar('.$value['id'].')">';
            echo '<i class="icon-pencil"></i></a>&nbsp;&nbsp;';
            echo '<a data-original-title="Eliminar" class="tip-top" href="#myModal" data-toggle="modal" onclick="elimina('.$value['id'].')">';
            echo '<i class="icon-trash"></i></a>';
            echo '</td>';
        ?>   
        <?php 
	echo "<td>".$value['demo1']."</td>";
	echo "<td>".$this->FechaMostrar($value['fecha'])."</td>";
	echo "<td>".$value['telefono']."</td>";
	echo "<td>".$value['direccion']."</td>";
	echo "<td>".$value['correo']."</td>";
	echo "<td>".$value['trabajo']."</td>";
	echo "<td>".$value['sueldo']."</td>";
	echo "<td>".$value['pais']."</td>";
	echo "<td>".$value['hijos']."</td>";
	echo "<td>".$this->FechaMostrar($value['nacimiento'])."</td>";
	echo "<td>".$value['dni']."</td>";
	echo "</tr>";
	?>
        <?php
        }
        echo '</tbody>';
        ?>
    </table>
</div>
</div>    
<?=$this->partial('_partials/modal.phtml',array('model' => $this->model));?>