<?=$this->partial('_partials/mensajes.phtml',array('messages' => $this->messages,'tipoMessages' => $this->tipoMessages));?>
<div class="widget-box">
    <div class="widget-title">	
        <h5><?=$this->active?></h5>
    </div>
<div class="widget-content nopadding">
    <table id='tabla' class="table table-condensed table-bordered" >
        <thead>
        <tr><th></th><th>Nombre</th><th>Apellido_paterno</th><th>Apellido_materno</th><th>Sexo</th><th>Tipo_doc</th><th>Num_doc</th><th>Telefono</th><th>Celular</th><th>Sueldo</th><th>Direccion</th><th>Fecha_nacimiento</th><th>Fh_registro</th></tr>
        </thead>
        <?php
        echo '<tbody>';
        foreach ($this->data as $value) {
            $estado = 'checkmark.png';
            echo '<tr>';
            echo '<td width=5% class="taskOptions">';
            echo '<a data-original-title="Editar" class="tip-top" href="#myModal" data-toggle="modal" onclick="editar('.$value['id'].')">';
            echo '<i class="icon-pencil"></i></a>&nbsp;&nbsp;';
            echo '<a data-original-title="Eliminar" class="tip-top" href="#myModal" data-toggle="modal" onclick="elimina('.$value['id'].')">';
            echo '<i class="icon-trash"></i></a>';
            echo '</td>';
        ?>   
        <?php 
	echo "<td>".$value['nombre']."</td>";
	echo "<td>".$value['apellido_paterno']."</td>";
	echo "<td>".$value['apellido_materno']."</td>";
	echo "<td>".$value['sexo']."</td>";
	echo "<td>".$value['tipo_doc']."</td>";
	echo "<td>".$value['num_doc']."</td>";
	echo "<td>".$value['telefono']."</td>";
	echo "<td>".$value['celular']."</td>";
	echo "<td>".$value['sueldo']."</td>";
	echo "<td>".$value['direccion']."</td>";
	echo "<td>".$this->FechaMostrar($value['fecha_nacimiento'])."</td>";
	echo "<td>".$this->FechaMostrar($value['fh_registro'])."</td>";
	echo "</tr>";
	?>
        <?php
        }
        echo '</tbody>';
        ?>
    </table>
</div>
</div>    
<?=$this->partial('_partials/modal.phtml',array('model' => $this->model));?>