<?=$this->partial('_partials/mensajes.phtml',array('messages' => $this->messages,'tipoMessages' => $this->tipoMessages));?>
<div class="widget-box">
    <div class="widget-title">	
        <h5><?=$this->active?></h5>
    </div>
<div class="widget-content nopadding">
    <table id='tabla' class="table table-condensed table-bordered" >
        <thead>
        <tr><th></th><th>Subtotal</th><th>Igv</th><th>Total</th><th>Estado</th><th>Entregado</th><th>Fecha_genera</th><th>Fecha_entrega</th><th>Id_usuario</th><th>Usuario_atendio</th></tr>
        </thead>
        <?php
        echo '<tbody>';
        foreach ($this->data as $value) {
            $estado = 'checkmark.png';
            echo '<tr>';
            echo '<td width=5% class="taskOptions">';
            echo '<a data-original-title="Editar" class="tip-top" href="#myModal" data-toggle="modal" onclick="editar('.$value['id'].')">';
            echo '<i class="icon-pencil"></i></a>&nbsp;&nbsp;';
            echo '<a data-original-title="Eliminar" class="tip-top" href="#myModal" data-toggle="modal" onclick="elimina('.$value['id'].')">';
            echo '<i class="icon-trash"></i></a>';
            echo '</td>';
        ?>   
        <?php 
	echo "<td>".$value['subtotal']."</td>";
	echo "<td>".$value['igv']."</td>";
	echo "<td>".$value['total']."</td>";
	echo "<td>".$value['estado']."</td>";
	echo "<td>".$value['entregado']."</td>";
	echo "<td>".$value['fecha_genera']."</td>";
	echo "<td>".$value['fecha_entrega']."</td>";
	echo "<td>".$value['id_usuario']."</td>";
	echo "<td>".$value['usuario_atendio']."</td>";
	echo "</tr>";
	?>
        <?php
        }
        echo '</tbody>';
        ?>
    </table>
</div>
</div>    
<?=$this->partial('_partials/modal.phtml',array('model' => $this->model));?>