<?=$this->partial('_partials/mensajes.phtml',array('messages' => $this->messages,'tipoMessages' => $this->tipoMessages));?>
<div class="widget-box">
    <div class="widget-title">	
        <h5><?=$this->active?></h5>
    </div>
<div class="widget-content nopadding">
    <table id='tabla' class="table table-condensed table-bordered" >
        <thead>
            <tr><th></th><th>Nombre</th><th>Inicio</th><th>Fin</th><th>Mapeo de puesto</th><th>Estado</th><th>Entidad</th></tr>
        </thead>
        <?php
        echo '<tbody>';
        foreach ($this->data as $value) {
            $estado = 'checkmark.png';
            echo '<tr>';
            echo '<td width=5% class="taskOptions">';
            echo '<a data-original-title="Editar" class="tip-top" href="#myModal" data-toggle="modal" onclick="editar('.$value['id_proyecto'].')">';
            echo '<i class="icon-pencil"></i></a>&nbsp;&nbsp;';
            echo '<a data-original-title="Eliminar" class="tip-top" href="#myModal" data-toggle="modal" onclick="elimina('.$value['id_proyecto'].')">';
            echo '<i class="icon-trash"></i></a>';
            echo '</td>';
        ?>   
        <?php 
	echo "<td>".$value['nombre']."</td>";
	echo "<td>".$this->FechaMostrar($value['inicio'])."</td>";
	echo "<td>".$this->FechaMostrar($value['fin'])."</td>";
        $mp = 'No';
        if ($value['mapa_puesto'] == 0)
                $mp = 'Sí';
        echo "<td><center>".$mp."</center></td>";
	if ($value['estado'] == Admin_MvcController::INACTIVO)
                $estado = 'error.png';
            echo '<td width=7%><center><span style=display:none>'.$value['estado'].'</span><img src='.SITE_URL.'/img/'.$estado.' width=15%><center></td>';
	echo "<td>".$value['entidad']."</td>";
	echo "</tr>";
	?>
        <?php
        }
        echo '</tbody>';
        ?>
    </table>
</div>
</div>    
<?=$this->partial('_partials/modal.phtml',array('model' => $this->model));?>