<?=$this->partial('_partials/mensajes.phtml',array('messages' => $this->messages,'tipoMessages' => $this->tipoMessages));?>
<div class="col-sm-6">
<div class="tabbable inline">
<ul class="nav nav-tabs tab-bricky" id="myTab">
<li class="active">
<a data-toggle="tab" href="#panel_tab2_example1">
Órgano
</a>
</li>
<li class="">
<a data-toggle="tab" href="#panel_tab2_example2">
Unidad orgánica
</a>
</li>
</ul>
<div class="tab-content" style="height:380px">
<div id="panel_tab2_example1" class="tab-pane active"> 
 <a href="#myModal" id="btnOpen" role="button" class="btn tip-right" title="Nuevo órgano" onclick="nuevoRegistro('puesto')" data-toggle="modal">
    <li class="icon-plus-sign"></li>Nuevo órgano
</a>
<div class="widget-content nopadding">
    <table id='tabla' class="table table-condensed table-bordered" >
        <thead>
            <tr><th></th><th>Naturaleza</th><th>Órgano</th></tr>
        </thead>
        <?php
        echo '<tbody>';
        foreach ($this->data as $value) {
            $estado = 'checkmark.png';
            echo '<tr>';
            echo '<td width=5% class="taskOptions">';
            echo '<a data-original-title="Editar" class="tip-top" href="#myModal" data-toggle="modal" onclick="editar('.$value['id_organigrama'].')">';
            echo '<i class="icon-pencil"></i></a>&nbsp;&nbsp;';
            echo '<a data-original-title="Eliminar" class="tip-top" href="#myModal" data-toggle="modal" onclick="elimina('.$value['id_organigrama'].')">';
            echo '<i class="icon-trash"></i></a>';
            echo '</td>';
            echo '<td>'.$value['natuorganica'].'</td>';
            echo '<td>'.$value['organo'].'</td>';
            if ($value['estado'] == Admin_MvcController::INACTIVO)
                $estado = 'error.png';
            echo '<td width=7%><center><span style=display:none>'.$value['estado'].'</span><img src='.SITE_URL.'/img/'.$estado.' width=15%><center></td>';
            echo '</tr>';
        }
        echo '</tbody>';
        ?>
    </table>
</div>

</div>
    

<div id="panel_tab2_example2" class="tab-pane">
<p>
Unidad orgánica
</p>
</div>
</div>
</div>
</div>
<?=$this->partial('_partials/modal.phtml',array('model' => $this->model));?>
<div id="data" style="display: none">
    <table class="tejem">
    <tr>
        <td>Num</td>
            <td>
                <select class="naturaleza">
                    <option value="">Seleccione</option>
                    <option value="M">Masculino</option>
                    <option value="F">Femenino</option>
                </select>
            </td>
            <td><input type="text" class="nombre" /></td>
            <td class="eliminar">Eliminar</td>
    </tr>
    </table>
</div>