<style>
    #usuario,#usuario_chzn
    {
        width: 250px;
        font-size:10pt
    }  
    #proyecto,#proyecto_chzn
    {
        width: 440px;
        font-size:10pt
    }       
</style>
<?=$this->partial('_partials/mensajes.phtml',array('messages' => $this->messages,'tipoMessages' => $this->tipoMessages));?>
<div class="widget-box">
    <div class="widget-title">	
        <h5><?=$this->active?></h5>
    </div>
<div class="widget-content nopadding" style="height:360px">
<select id="usuario" name="usuario">
<option value=''>[Seleccione usuario]</option>
<?php foreach ($this->usuarios as $val){
   echo "<option value=".$val['id'].">".$val['nombres']." ".$val['apellidos']."(".$val['nom_rol'].")</option>"; 
}?>
</select>
<select id="proyecto" name="proyecto">
<option value=''>[Seleccione proyecto]</option>
<?php foreach ($this->proyecto as $val){
   echo "<option value=".$val['id_proyecto'].">".$val['nombre']."(".$val['entidad'].")</option>"; 
}?>
</select>
<input type="submit" id="grabarPermisos" class="btn btn-inverse" value="Grabar permisos" style="margin-top:-23px" />
<table id='' class="table table-condensed table-bordered" style="width: 60%">
    <thead>
        <tr><th>#</th><th>Nombre</th><th>Estado</th></tr>
    </thead>
    <tbody id="permisos">
    </tbody>
</table>
<input type="hidden" id="controla" name="controla" value="0">
</div>
<?=$this->partial('_partials/modal.phtml',array('model' => $this->model));?>
