<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><?=TITLE?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <link rel="stylesheet" href="<?=SITE_URL?>/css/bootstrap.min.css" />
    <link rel="stylesheet" href="<?=SITE_URL?>/css/bootstrap-responsive.min.css" />
    <link rel="stylesheet" href="<?=SITE_URL?>/css/unicorn.login.css" />
    <link rel="stylesheet" href="<?=SITE_URL?>/css/mensajes.css" />
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="<?=SITE_URL?>/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?=SITE_URL?>/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?=SITE_URL?>/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?=SITE_URL?>/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="<?=SITE_URL?>/ico/apple-touch-icon-57-precomposed.png">
    <?=$this->headLink() ?>
    
    <script src="<?=SITE_URL?>/js/jquery.min.js"></script>  
    <script src="<?=SITE_URL?>/js/jquery.validate.js"></script>
    <script src="<?=SITE_URL?>/js/web/main.js"></script>
    <script src="<?=SITE_URL?>/js/web/login.js"></script>
    <?=$this->headScript() ?>
  </head>
  <body>
    <div id="logo">
        <img src="<?=SITE_URL?>/img/logo.png" alt="" />
    </div>
    <?=$this->layout()->content?>
  </body>
</html>

