<script type="text/javascript">
    google.load("visualization", "1", {packages: ["corechart"]});
    google.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = google.visualization.arrayToDataTable([['Año', 'Atendido'], [2014, 12], [2015, 13]]);

        var options = {
            title: 'Personas discapacitadas por estado de trámite',
            hAxis: {title: 'Año', titleTextStyle: {color: 'red'}}
        };

        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    }
</script>
<center>
    <div id="chart_div" style="width: 900px; height: 400px;"></div>
</center>


