<?=$this->partial('_partials/mensajes.phtml',array('messages' => $this->messages,'tipoMessages' => $this->tipoMessages));?>

<div class="tabbable inline">
<ul class="nav nav-tabs tab-bricky" id="myTab">
<?php $active = '';if ($this->tipo == 'organo')$active = 'active';?>
<li class="active">
<a data-toggle="tab" href="#panel_tab2_example1">
Órgano
</a>
</li>
<?php $active = '';if ($this->tipo == 'unidad')$active = 'active';?>
<li class="">
<a data-toggle="tab" href="#panel_tab2_example2">
Unidad orgánica
</a>
</li>
</ul>

<div class="tab-content" style="">
<div id="panel_tab2_example1" class="tab-pane active"> 
<div class="widget-box">
<a href="#myModal" id="btnOpen" role="button" class="btn tip-right" title="Nuevo órgano" onclick="nuevoRegistro('organo')" data-toggle="modal">
    <li class="icon-plus-sign"></li>Nuevo órgano
</a>
<a href="#myModal" id="btnOpen" role="button" class="btn tip-right" title="Grabar registros" onclick="grabarDatos('organo')" data-toggle="modal">
    <li class="icon-check"></li>Grabar registros
</a>
<div class="widget-content nopadding">
    <table id='tablaorgano' class="table table-condensed table-bordered" style="">
        <thead>
            <tr><th width="20%"></th><th width="15%">Naturaleza</th><th width="60%">Órgano</th><th width="5%">Siglas</th></tr>
        </thead>
        <?php
        echo '<tbody>';
        $contador = 0;
        foreach ($this->organo as $value) {
            $contador++;
            $estado = 'checkmark.png';
            echo '<tr data-organo='.$value['id_organo'].'>';
            echo '<td width=5% class="taskOptions">'.'<span style="display:none">'.$value['organo']."</span>";
            echo '<a data-original-title="Eliminar" class="tip-top" href="#myModal" data-toggle="modal" onclick="eliminaRegistro('.$value['id_organo'].','."'"."organo"."')".'">';
            echo '<i class="icon-trash"></i></a>';
            echo '</td>';
            echo '<td width=15%>'.$this->Naturaleza($value['codigo_natuorganica'],$contador).'</td>';
            echo '<td width="60%"><input type=organo value="'.$value['organo'].'" style="width:100%"></td>';
            echo '<td><input type=organo value="'.$value['siglas'].'" style="width:50%"></td>';
            echo '</tr>';
        }
        echo '</tbody>';
        ?>
    </table>
</div>
</div>
</div>

<div id="panel_tab2_example2" class="tab-pane">
<div class="widget-box">
<a href="#myModal" id="btnOpen" role="button" class="btn tip-right" title="Nueva unidad orgánica" onclick="nuevoRegistro('unidad')" data-toggle="modal">
    <li class="icon-plus-sign"></li>Nueva unidad orgánica
</a>
<a href="#myModal" id="btnOpen" role="button" class="btn tip-right" title="Grabar registros" onclick="grabarDatos('unidad')" data-toggle="modal">
    <li class="icon-check"></li>Grabar registros
</a>
<div class="widget-content nopadding">
    <table id='tablaunidad' class="table table-condensed table-bordered" style="">
        <thead>
            <tr><th width="20%"></th><th width="15%">Órgano</th><th width="60%">Unidad Orgánica</th><th width="5%">Siglas</th></tr>
        </thead>
        <?php
        echo '<tbody>';
        $contador = 0;
        foreach ($this->unidad as $value) {
            $contador++;
            $estado = 'checkmark.png';
            echo '<tr data-unidad='.$value['id_uorganica'].'>';
            echo '<td width=5% class="taskOptions">'.'<span style="display:none">'.$value['descripcion']."</span>";;
            echo '<a data-original-title="Eliminar" class="tip-top" href="#myModal" data-toggle="modal" onclick="eliminaRegistro('.$value['id_uorganica'].','."'"."unidad"."')".'">';
            echo '<i class="icon-trash"></i></a>';
            echo '</td>';
            echo '<td width="15%">'.$this->Organo($value['id_organo'],$value['id_proyecto'],$contador).'</td>';
            echo '<td width="60%"><input type=organo value="'.$value['descripcion'].'" style="width:100%"></td>';
            echo '<td><input type=organo value="'.$value['siglas'].'" style="width:50%"></td>';
            echo '</tr>';
        }
        echo '</tbody>';
        ?>
    </table>
</div>
</div>
</div>
</div>
</div>
<?=$this->partial('_partials/modal.phtml',array('model' => $this->model));?>