<?=$this->partial('_partials/mensajes.phtml',array('messages' => $this->messages,'tipoMessages' => $this->tipoMessages));?>
<div class="widget-box">
    <div class="widget-title">	
        <h5><?=$this->active?></h5>
    </div>
<div class="widget-content nopadding">
<select id="organo" name="organo">
<option value=''>[Seleccione órgano]</option>
<?php foreach ($this->organo as $val){
   echo "<option value=".$val['id_organo'].">".$val['organo']."</option>"; 
}?>
</select>    

<div id="capa"></div>
    
 
</div>
</div>
<?=$this->partial('_partials/modal.phtml',array('model' => $this->model));?>